### ISSUE TITLE
JSONDecodeError: Expecting value

### ISSUE THREAD

**Issue by B3SCH** [TheSaltMaker/lil_insta_scraper#1]
Ran the following code:
`python3 ~/user/instascraper.py -s <session> -t <target>`

Received the following error:
```
Traceback (most recent call last):
  File "/home/user/lil_insta_scraper/instascraper.py", line 167, in <module>
    userid = UserID(target) #give a value to userid for the next function
  File "/home/user/lil_insta_scraper/instascraper.py", line 55, in UserID
    info = json.loads(r.text)
  File "/home/user/anaconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/user/anaconda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/user/anaconda3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Error arises within UserID().
`requests.get(url.format(target))` returns HTML for `url = hxxps://www.instagram.com/{target}/?__a=1`, which cannot be read as JSON. What is appropriate workaround or fix for this problem?

**Comment by TheSaltMaker** [comment]
The problem is that it run perfectly on my compuer and the second problem is that you can check out that hxxps://instagram.com/target/?__a=1 doesn't contain any html code... It only contain JSON... 

All i can do to help you is to read try to git clone the code again (I updated it today) maybe you won't have problems anymore

**Comment by B3SCH** [comment]
Thanks for the reply. Will continue to troubleshoot on my end.
Agreed, hxxps://instagram.com/target/?__a=1 is JSON, which is why am confused why `requests` returns HTML.
What version of `requests` does the code rely on? Am using requests v2.22.0

**Comment by B3SCH** [comment]
It is likely that Instagram detects proxy/VPN use and blocks `requests` from accessing JSON. If no proxy/VPN use detected, then getting JSON should work.
Is this a plausible explanation? If so, then we can close this issue. Thank you

**Comment by TheSaltMaker** [comment]
I'm actually using the 2.23.0 version of requests but i think the problem is coming from your VPN/proxy because during an update I was working from a VPN and i encountered the same problem. I don' t know why at the moment but you can't use this script with a VPN/proxy
